apiVersion: v1
kind: Pod
metadata:
  name: apache-benchmark-pod
  labels:
    app: apache
    role: client
spec:
  containers:
  - name: ab-container
    image: httpd:2.4
    command: ["sleep", "infinity"]
    stdin: true
    tty: true