apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: nginx
    role: server  
spec:
  containers:
  - name: httpd-container
    image: httpd:latest
    ports:
    - containerPort: 80