---
apiVersion: v1
kind: Service
metadata:
  name: iperfserver
  labels: 
    app.kubernetes.io/name: iperfserver
spec: 
  type: ClusterIP
  ports:
  - port: 8070
  selector:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperfserver
  labels:
    app.kubernetes.io/name: iperfserver
spec:
  replicas: 2
  selector:
    matchLabels:
      org: iperf
      class: server
      work: listen
  template:
    metadata:
      labels:
        org: iperf
        class: server
        work: listen
        app.kubernetes.io/name: iperfserver
    spec:
      containers:
      - name: iperfserver
        image: docker.io/networkstatic/iperf3 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperfclient
  labels:
    app.kubernetes.io/name: iperfclient
spec:
  replicas: 2
  selector:
    matchLabels:
      org: iperf
      class: client
      work: transmit
  template:
    metadata:
      labels:
        org: iperf
        class: client
        work: transmit
        app.kubernetes.io/name: iperfclient
    spec:
      containers:
      - name: iperfclient
        image: docker.io/networkstatic/iperf3         

