---
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  labels:
    app: iperf
    type: service
spec:
  ports:
  - name: iperftcp
    port: 5201
    protocol: TCP
  - name: iperfudp
    port: 5202
    protocol: UDP  
  - name: iperfhttp
    port: 80 
    protocol: TCP
  - name: iperfhttps
    port: 443
    protocol: TCP    
  selector:
    app: iperf
    role: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iperf
      role: server
  template:
    metadata:
      labels:
        app: iperf
        role: server
        type: pod
    spec:
      containers:
      - name: iperf-server
        image: networkstatic/iperf3
        command: ["iperf3", "-s"]
      - name: ping
        image: alpine
        command: ["sleep", "infinity"]
        args: ["tail", "-f", "/dev/null"]        
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-1
  labels:
    app: iperf
    type: pod 
    podnum: one 
    subject: cloud     
spec:
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ["sleep", "infinity"]
  - name: ping
    image: alpine
    command: ["sleep", "infinity"]
    args: ["tail", "-f", "/dev/null"]    
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-2
  labels:
    app: iperf
    type: pod 
    podnum: two 
    subject: network
spec:
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ["sleep", "infinity"]      
  - name: ping
    image: alpine
    command: ["sleep", "infinity"]
    args: ["tail", "-f", "/dev/null"]
